// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: chess_trade.proto

package trade

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Trade_H5Prepaid_FullMethodName                    = "/new_chess.Trade/h5Prepaid"
	Trade_AppPrepaid_FullMethodName                   = "/new_chess.Trade/AppPrepaid"
	Trade_JsapiPrepaid_FullMethodName                 = "/new_chess.Trade/jsapiPrepaid"
	Trade_JsapiRepaid_FullMethodName                  = "/new_chess.Trade/jsapiRepaid"
	Trade_QueryOrder_FullMethodName                   = "/new_chess.Trade/queryOrder"
	Trade_CancelOrder_FullMethodName                  = "/new_chess.Trade/cancelOrder"
	Trade_RefundOrder_FullMethodName                  = "/new_chess.Trade/refundOrder"
	Trade_WithdrawBankCard_FullMethodName             = "/new_chess.Trade/withdrawBankCard"
	Trade_QueryExtractOrder_FullMethodName            = "/new_chess.Trade/queryExtractOrder"
	Trade_SaveExtractConfig_FullMethodName            = "/new_chess.Trade/saveExtractConfig"
	Trade_GetExtractConfig_FullMethodName             = "/new_chess.Trade/getExtractConfig"
	Trade_SaveExtractUserConfig_FullMethodName        = "/new_chess.Trade/saveExtractUserConfig"
	Trade_GetExtractUserConfig_FullMethodName         = "/new_chess.Trade/getExtractUserConfig"
	Trade_GetExtractLogs_FullMethodName               = "/new_chess.Trade/getExtractLogs"
	Trade_CheckUserExtractRisk_FullMethodName         = "/new_chess.Trade/checkUserExtractRisk"
	Trade_MallBookNewSelfAccount_FullMethodName       = "/new_chess.Trade/mallBookNewSelfAccount"
	Trade_MallBookBindBankCard_FullMethodName         = "/new_chess.Trade/mallBookBindBankCard"
	Trade_MallBookUnbindBankCard_FullMethodName       = "/new_chess.Trade/mallBookUnbindBankCard"
	Trade_MallBookDeposit_FullMethodName              = "/new_chess.Trade/mallBookDeposit"
	Trade_MallBookTransfer_FullMethodName             = "/new_chess.Trade/mallBookTransfer"
	Trade_MallBookWithdraw_FullMethodName             = "/new_chess.Trade/mallBookWithdraw"
	Trade_MallBookCheckUserAccountInfo_FullMethodName = "/new_chess.Trade/mallBookCheckUserAccountInfo"
	Trade_GetNcountAccountInfo_FullMethodName         = "/new_chess.Trade/getNcountAccountInfo"
	Trade_SetPaymentSecret_FullMethodName             = "/new_chess.Trade/setPaymentSecret"
	Trade_GetOpenIDByCode_FullMethodName              = "/new_chess.Trade/getOpenIDByCode"
)

// TradeClient is the client API for Trade service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeClient interface {
	// h5预下单
	H5Prepaid(ctx context.Context, in *PrepaidReq, opts ...grpc.CallOption) (*H5PrepaidResp, error)
	// app下单
	AppPrepaid(ctx context.Context, in *PrepaidReq, opts ...grpc.CallOption) (*AppPrepaidResp, error)
	// jsapi预下单
	JsapiPrepaid(ctx context.Context, in *PrepaidReq, opts ...grpc.CallOption) (*JsapiPrepaidResp, error)
	// jsapi预支付
	JsapiRepaid(ctx context.Context, in *JsapiRepaidReq, opts ...grpc.CallOption) (*JsapiPrepaidResp, error)
	// 订单查询
	QueryOrder(ctx context.Context, in *QueryOrderReq, opts ...grpc.CallOption) (*QueryOrderResp, error)
	// 取消订单
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
	// 订单退款
	RefundOrder(ctx context.Context, in *RefundOrderReq, opts ...grpc.CallOption) (*RefundOrderResp, error)
	// mallbook账户提现至银行卡：先转账至子商户，子商户自动结算
	WithdrawBankCard(ctx context.Context, in *WithdrawBankCardReq, opts ...grpc.CallOption) (*WithdrawBankCardResp, error)
	// 提现订单查询
	QueryExtractOrder(ctx context.Context, in *QueryExtractOrderReq, opts ...grpc.CallOption) (*QueryExtractOrderResp, error)
	// 提现全局配置
	SaveExtractConfig(ctx context.Context, in *SaveExtractConfigReq, opts ...grpc.CallOption) (*SaveExtractConfigResp, error)
	// 获取提现全局配置
	GetExtractConfig(ctx context.Context, in *GetExtractConfigReq, opts ...grpc.CallOption) (*GetExtractConfigResp, error)
	// 提现用户配置
	SaveExtractUserConfig(ctx context.Context, in *SaveExtractUserConfigReq, opts ...grpc.CallOption) (*SaveExtractUserConfigResp, error)
	// 获取提现用户配置
	GetExtractUserConfig(ctx context.Context, in *GetExtractUserConfigReq, opts ...grpc.CallOption) (*GetExtractUserConfigResp, error)
	// 获取提现日志列表
	GetExtractLogs(ctx context.Context, in *GetExtractLogsReq, opts ...grpc.CallOption) (*GetExtractLogsResp, error)
	// 检查用户是否被提现封控
	CheckUserExtractRisk(ctx context.Context, in *CheckUserExtractRiskReq, opts ...grpc.CallOption) (*CheckUserExtractRiskResp, error)
	// mallbook个人开户
	MallBookNewSelfAccount(ctx context.Context, in *MallBookNewSelfAccountReq, opts ...grpc.CallOption) (*MallBookNewSelfAccountResp, error)
	// mallbook个人用户绑卡
	MallBookBindBankCard(ctx context.Context, in *MallBookBindBankCardReq, opts ...grpc.CallOption) (*MallBookBindBankCardResp, error)
	// mallbook个人用户解绑银行卡
	MallBookUnbindBankCard(ctx context.Context, in *MallBookUnbindBankCardReq, opts ...grpc.CallOption) (*MallBookUnbindBankCardResp, error)
	// mallbook充值
	MallBookDeposit(ctx context.Context, in *MallBookDepositReq, opts ...grpc.CallOption) (*MallBookDepositResp, error)
	// mallbook转账
	MallBookTransfer(ctx context.Context, in *MallBookTransferReq, opts ...grpc.CallOption) (*MallBookTransferResp, error)
	// mallbook提现
	MallBookWithdraw(ctx context.Context, in *MallBookWithdrawReq, opts ...grpc.CallOption) (*MallBookWithdrawResp, error)
	// mallbook查询用户账户信息
	MallBookCheckUserAccountInfo(ctx context.Context, in *MallBookCheckUserAccountInfoReq, opts ...grpc.CallOption) (*MallBookCheckUserAccountInfoResp, error)
	// 获取系统账户信息
	GetNcountAccountInfo(ctx context.Context, in *GetNcountAccountInfoReq, opts ...grpc.CallOption) (*GetNcountAccountInfoResp, error)
	// 设置支付密码
	SetPaymentSecret(ctx context.Context, in *SetPaymentSecretReq, opts ...grpc.CallOption) (*SetPaymentSecretResp, error)
	// 获取微信openid
	GetOpenIDByCode(ctx context.Context, in *GetOpenIDByCodeReq, opts ...grpc.CallOption) (*GetOpenIDByCodeResp, error)
}

type tradeClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeClient(cc grpc.ClientConnInterface) TradeClient {
	return &tradeClient{cc}
}

func (c *tradeClient) H5Prepaid(ctx context.Context, in *PrepaidReq, opts ...grpc.CallOption) (*H5PrepaidResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(H5PrepaidResp)
	err := c.cc.Invoke(ctx, Trade_H5Prepaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) AppPrepaid(ctx context.Context, in *PrepaidReq, opts ...grpc.CallOption) (*AppPrepaidResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppPrepaidResp)
	err := c.cc.Invoke(ctx, Trade_AppPrepaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) JsapiPrepaid(ctx context.Context, in *PrepaidReq, opts ...grpc.CallOption) (*JsapiPrepaidResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsapiPrepaidResp)
	err := c.cc.Invoke(ctx, Trade_JsapiPrepaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) JsapiRepaid(ctx context.Context, in *JsapiRepaidReq, opts ...grpc.CallOption) (*JsapiPrepaidResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsapiPrepaidResp)
	err := c.cc.Invoke(ctx, Trade_JsapiRepaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) QueryOrder(ctx context.Context, in *QueryOrderReq, opts ...grpc.CallOption) (*QueryOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryOrderResp)
	err := c.cc.Invoke(ctx, Trade_QueryOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResp)
	err := c.cc.Invoke(ctx, Trade_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) RefundOrder(ctx context.Context, in *RefundOrderReq, opts ...grpc.CallOption) (*RefundOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundOrderResp)
	err := c.cc.Invoke(ctx, Trade_RefundOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) WithdrawBankCard(ctx context.Context, in *WithdrawBankCardReq, opts ...grpc.CallOption) (*WithdrawBankCardResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawBankCardResp)
	err := c.cc.Invoke(ctx, Trade_WithdrawBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) QueryExtractOrder(ctx context.Context, in *QueryExtractOrderReq, opts ...grpc.CallOption) (*QueryExtractOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryExtractOrderResp)
	err := c.cc.Invoke(ctx, Trade_QueryExtractOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) SaveExtractConfig(ctx context.Context, in *SaveExtractConfigReq, opts ...grpc.CallOption) (*SaveExtractConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveExtractConfigResp)
	err := c.cc.Invoke(ctx, Trade_SaveExtractConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) GetExtractConfig(ctx context.Context, in *GetExtractConfigReq, opts ...grpc.CallOption) (*GetExtractConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExtractConfigResp)
	err := c.cc.Invoke(ctx, Trade_GetExtractConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) SaveExtractUserConfig(ctx context.Context, in *SaveExtractUserConfigReq, opts ...grpc.CallOption) (*SaveExtractUserConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveExtractUserConfigResp)
	err := c.cc.Invoke(ctx, Trade_SaveExtractUserConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) GetExtractUserConfig(ctx context.Context, in *GetExtractUserConfigReq, opts ...grpc.CallOption) (*GetExtractUserConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExtractUserConfigResp)
	err := c.cc.Invoke(ctx, Trade_GetExtractUserConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) GetExtractLogs(ctx context.Context, in *GetExtractLogsReq, opts ...grpc.CallOption) (*GetExtractLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExtractLogsResp)
	err := c.cc.Invoke(ctx, Trade_GetExtractLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) CheckUserExtractRisk(ctx context.Context, in *CheckUserExtractRiskReq, opts ...grpc.CallOption) (*CheckUserExtractRiskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserExtractRiskResp)
	err := c.cc.Invoke(ctx, Trade_CheckUserExtractRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) MallBookNewSelfAccount(ctx context.Context, in *MallBookNewSelfAccountReq, opts ...grpc.CallOption) (*MallBookNewSelfAccountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MallBookNewSelfAccountResp)
	err := c.cc.Invoke(ctx, Trade_MallBookNewSelfAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) MallBookBindBankCard(ctx context.Context, in *MallBookBindBankCardReq, opts ...grpc.CallOption) (*MallBookBindBankCardResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MallBookBindBankCardResp)
	err := c.cc.Invoke(ctx, Trade_MallBookBindBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) MallBookUnbindBankCard(ctx context.Context, in *MallBookUnbindBankCardReq, opts ...grpc.CallOption) (*MallBookUnbindBankCardResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MallBookUnbindBankCardResp)
	err := c.cc.Invoke(ctx, Trade_MallBookUnbindBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) MallBookDeposit(ctx context.Context, in *MallBookDepositReq, opts ...grpc.CallOption) (*MallBookDepositResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MallBookDepositResp)
	err := c.cc.Invoke(ctx, Trade_MallBookDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) MallBookTransfer(ctx context.Context, in *MallBookTransferReq, opts ...grpc.CallOption) (*MallBookTransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MallBookTransferResp)
	err := c.cc.Invoke(ctx, Trade_MallBookTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) MallBookWithdraw(ctx context.Context, in *MallBookWithdrawReq, opts ...grpc.CallOption) (*MallBookWithdrawResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MallBookWithdrawResp)
	err := c.cc.Invoke(ctx, Trade_MallBookWithdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) MallBookCheckUserAccountInfo(ctx context.Context, in *MallBookCheckUserAccountInfoReq, opts ...grpc.CallOption) (*MallBookCheckUserAccountInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MallBookCheckUserAccountInfoResp)
	err := c.cc.Invoke(ctx, Trade_MallBookCheckUserAccountInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) GetNcountAccountInfo(ctx context.Context, in *GetNcountAccountInfoReq, opts ...grpc.CallOption) (*GetNcountAccountInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNcountAccountInfoResp)
	err := c.cc.Invoke(ctx, Trade_GetNcountAccountInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) SetPaymentSecret(ctx context.Context, in *SetPaymentSecretReq, opts ...grpc.CallOption) (*SetPaymentSecretResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPaymentSecretResp)
	err := c.cc.Invoke(ctx, Trade_SetPaymentSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeClient) GetOpenIDByCode(ctx context.Context, in *GetOpenIDByCodeReq, opts ...grpc.CallOption) (*GetOpenIDByCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOpenIDByCodeResp)
	err := c.cc.Invoke(ctx, Trade_GetOpenIDByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeServer is the server API for Trade service.
// All implementations must embed UnimplementedTradeServer
// for forward compatibility.
type TradeServer interface {
	// h5预下单
	H5Prepaid(context.Context, *PrepaidReq) (*H5PrepaidResp, error)
	// app下单
	AppPrepaid(context.Context, *PrepaidReq) (*AppPrepaidResp, error)
	// jsapi预下单
	JsapiPrepaid(context.Context, *PrepaidReq) (*JsapiPrepaidResp, error)
	// jsapi预支付
	JsapiRepaid(context.Context, *JsapiRepaidReq) (*JsapiPrepaidResp, error)
	// 订单查询
	QueryOrder(context.Context, *QueryOrderReq) (*QueryOrderResp, error)
	// 取消订单
	CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderResp, error)
	// 订单退款
	RefundOrder(context.Context, *RefundOrderReq) (*RefundOrderResp, error)
	// mallbook账户提现至银行卡：先转账至子商户，子商户自动结算
	WithdrawBankCard(context.Context, *WithdrawBankCardReq) (*WithdrawBankCardResp, error)
	// 提现订单查询
	QueryExtractOrder(context.Context, *QueryExtractOrderReq) (*QueryExtractOrderResp, error)
	// 提现全局配置
	SaveExtractConfig(context.Context, *SaveExtractConfigReq) (*SaveExtractConfigResp, error)
	// 获取提现全局配置
	GetExtractConfig(context.Context, *GetExtractConfigReq) (*GetExtractConfigResp, error)
	// 提现用户配置
	SaveExtractUserConfig(context.Context, *SaveExtractUserConfigReq) (*SaveExtractUserConfigResp, error)
	// 获取提现用户配置
	GetExtractUserConfig(context.Context, *GetExtractUserConfigReq) (*GetExtractUserConfigResp, error)
	// 获取提现日志列表
	GetExtractLogs(context.Context, *GetExtractLogsReq) (*GetExtractLogsResp, error)
	// 检查用户是否被提现封控
	CheckUserExtractRisk(context.Context, *CheckUserExtractRiskReq) (*CheckUserExtractRiskResp, error)
	// mallbook个人开户
	MallBookNewSelfAccount(context.Context, *MallBookNewSelfAccountReq) (*MallBookNewSelfAccountResp, error)
	// mallbook个人用户绑卡
	MallBookBindBankCard(context.Context, *MallBookBindBankCardReq) (*MallBookBindBankCardResp, error)
	// mallbook个人用户解绑银行卡
	MallBookUnbindBankCard(context.Context, *MallBookUnbindBankCardReq) (*MallBookUnbindBankCardResp, error)
	// mallbook充值
	MallBookDeposit(context.Context, *MallBookDepositReq) (*MallBookDepositResp, error)
	// mallbook转账
	MallBookTransfer(context.Context, *MallBookTransferReq) (*MallBookTransferResp, error)
	// mallbook提现
	MallBookWithdraw(context.Context, *MallBookWithdrawReq) (*MallBookWithdrawResp, error)
	// mallbook查询用户账户信息
	MallBookCheckUserAccountInfo(context.Context, *MallBookCheckUserAccountInfoReq) (*MallBookCheckUserAccountInfoResp, error)
	// 获取系统账户信息
	GetNcountAccountInfo(context.Context, *GetNcountAccountInfoReq) (*GetNcountAccountInfoResp, error)
	// 设置支付密码
	SetPaymentSecret(context.Context, *SetPaymentSecretReq) (*SetPaymentSecretResp, error)
	// 获取微信openid
	GetOpenIDByCode(context.Context, *GetOpenIDByCodeReq) (*GetOpenIDByCodeResp, error)
	mustEmbedUnimplementedTradeServer()
}

// UnimplementedTradeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeServer struct{}

func (UnimplementedTradeServer) H5Prepaid(context.Context, *PrepaidReq) (*H5PrepaidResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method H5Prepaid not implemented")
}
func (UnimplementedTradeServer) AppPrepaid(context.Context, *PrepaidReq) (*AppPrepaidResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppPrepaid not implemented")
}
func (UnimplementedTradeServer) JsapiPrepaid(context.Context, *PrepaidReq) (*JsapiPrepaidResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JsapiPrepaid not implemented")
}
func (UnimplementedTradeServer) JsapiRepaid(context.Context, *JsapiRepaidReq) (*JsapiPrepaidResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JsapiRepaid not implemented")
}
func (UnimplementedTradeServer) QueryOrder(context.Context, *QueryOrderReq) (*QueryOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrder not implemented")
}
func (UnimplementedTradeServer) CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedTradeServer) RefundOrder(context.Context, *RefundOrderReq) (*RefundOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundOrder not implemented")
}
func (UnimplementedTradeServer) WithdrawBankCard(context.Context, *WithdrawBankCardReq) (*WithdrawBankCardResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawBankCard not implemented")
}
func (UnimplementedTradeServer) QueryExtractOrder(context.Context, *QueryExtractOrderReq) (*QueryExtractOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryExtractOrder not implemented")
}
func (UnimplementedTradeServer) SaveExtractConfig(context.Context, *SaveExtractConfigReq) (*SaveExtractConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveExtractConfig not implemented")
}
func (UnimplementedTradeServer) GetExtractConfig(context.Context, *GetExtractConfigReq) (*GetExtractConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtractConfig not implemented")
}
func (UnimplementedTradeServer) SaveExtractUserConfig(context.Context, *SaveExtractUserConfigReq) (*SaveExtractUserConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveExtractUserConfig not implemented")
}
func (UnimplementedTradeServer) GetExtractUserConfig(context.Context, *GetExtractUserConfigReq) (*GetExtractUserConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtractUserConfig not implemented")
}
func (UnimplementedTradeServer) GetExtractLogs(context.Context, *GetExtractLogsReq) (*GetExtractLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtractLogs not implemented")
}
func (UnimplementedTradeServer) CheckUserExtractRisk(context.Context, *CheckUserExtractRiskReq) (*CheckUserExtractRiskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserExtractRisk not implemented")
}
func (UnimplementedTradeServer) MallBookNewSelfAccount(context.Context, *MallBookNewSelfAccountReq) (*MallBookNewSelfAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MallBookNewSelfAccount not implemented")
}
func (UnimplementedTradeServer) MallBookBindBankCard(context.Context, *MallBookBindBankCardReq) (*MallBookBindBankCardResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MallBookBindBankCard not implemented")
}
func (UnimplementedTradeServer) MallBookUnbindBankCard(context.Context, *MallBookUnbindBankCardReq) (*MallBookUnbindBankCardResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MallBookUnbindBankCard not implemented")
}
func (UnimplementedTradeServer) MallBookDeposit(context.Context, *MallBookDepositReq) (*MallBookDepositResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MallBookDeposit not implemented")
}
func (UnimplementedTradeServer) MallBookTransfer(context.Context, *MallBookTransferReq) (*MallBookTransferResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MallBookTransfer not implemented")
}
func (UnimplementedTradeServer) MallBookWithdraw(context.Context, *MallBookWithdrawReq) (*MallBookWithdrawResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MallBookWithdraw not implemented")
}
func (UnimplementedTradeServer) MallBookCheckUserAccountInfo(context.Context, *MallBookCheckUserAccountInfoReq) (*MallBookCheckUserAccountInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MallBookCheckUserAccountInfo not implemented")
}
func (UnimplementedTradeServer) GetNcountAccountInfo(context.Context, *GetNcountAccountInfoReq) (*GetNcountAccountInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNcountAccountInfo not implemented")
}
func (UnimplementedTradeServer) SetPaymentSecret(context.Context, *SetPaymentSecretReq) (*SetPaymentSecretResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPaymentSecret not implemented")
}
func (UnimplementedTradeServer) GetOpenIDByCode(context.Context, *GetOpenIDByCodeReq) (*GetOpenIDByCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpenIDByCode not implemented")
}
func (UnimplementedTradeServer) mustEmbedUnimplementedTradeServer() {}
func (UnimplementedTradeServer) testEmbeddedByValue()               {}

// UnsafeTradeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeServer will
// result in compilation errors.
type UnsafeTradeServer interface {
	mustEmbedUnimplementedTradeServer()
}

func RegisterTradeServer(s grpc.ServiceRegistrar, srv TradeServer) {
	// If the following call pancis, it indicates UnimplementedTradeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trade_ServiceDesc, srv)
}

func _Trade_H5Prepaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepaidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).H5Prepaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_H5Prepaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).H5Prepaid(ctx, req.(*PrepaidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_AppPrepaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepaidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).AppPrepaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_AppPrepaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).AppPrepaid(ctx, req.(*PrepaidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_JsapiPrepaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepaidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).JsapiPrepaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_JsapiPrepaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).JsapiPrepaid(ctx, req.(*PrepaidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_JsapiRepaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsapiRepaidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).JsapiRepaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_JsapiRepaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).JsapiRepaid(ctx, req.(*JsapiRepaidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_QueryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).QueryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_QueryOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).QueryOrder(ctx, req.(*QueryOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_RefundOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).RefundOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_RefundOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).RefundOrder(ctx, req.(*RefundOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_WithdrawBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawBankCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).WithdrawBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_WithdrawBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).WithdrawBankCard(ctx, req.(*WithdrawBankCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_QueryExtractOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryExtractOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).QueryExtractOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_QueryExtractOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).QueryExtractOrder(ctx, req.(*QueryExtractOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_SaveExtractConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveExtractConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).SaveExtractConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_SaveExtractConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).SaveExtractConfig(ctx, req.(*SaveExtractConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_GetExtractConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtractConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).GetExtractConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_GetExtractConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).GetExtractConfig(ctx, req.(*GetExtractConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_SaveExtractUserConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveExtractUserConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).SaveExtractUserConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_SaveExtractUserConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).SaveExtractUserConfig(ctx, req.(*SaveExtractUserConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_GetExtractUserConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtractUserConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).GetExtractUserConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_GetExtractUserConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).GetExtractUserConfig(ctx, req.(*GetExtractUserConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_GetExtractLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtractLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).GetExtractLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_GetExtractLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).GetExtractLogs(ctx, req.(*GetExtractLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_CheckUserExtractRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserExtractRiskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).CheckUserExtractRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_CheckUserExtractRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).CheckUserExtractRisk(ctx, req.(*CheckUserExtractRiskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_MallBookNewSelfAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MallBookNewSelfAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).MallBookNewSelfAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_MallBookNewSelfAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).MallBookNewSelfAccount(ctx, req.(*MallBookNewSelfAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_MallBookBindBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MallBookBindBankCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).MallBookBindBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_MallBookBindBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).MallBookBindBankCard(ctx, req.(*MallBookBindBankCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_MallBookUnbindBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MallBookUnbindBankCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).MallBookUnbindBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_MallBookUnbindBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).MallBookUnbindBankCard(ctx, req.(*MallBookUnbindBankCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_MallBookDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MallBookDepositReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).MallBookDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_MallBookDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).MallBookDeposit(ctx, req.(*MallBookDepositReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_MallBookTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MallBookTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).MallBookTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_MallBookTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).MallBookTransfer(ctx, req.(*MallBookTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_MallBookWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MallBookWithdrawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).MallBookWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_MallBookWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).MallBookWithdraw(ctx, req.(*MallBookWithdrawReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_MallBookCheckUserAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MallBookCheckUserAccountInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).MallBookCheckUserAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_MallBookCheckUserAccountInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).MallBookCheckUserAccountInfo(ctx, req.(*MallBookCheckUserAccountInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_GetNcountAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNcountAccountInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).GetNcountAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_GetNcountAccountInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).GetNcountAccountInfo(ctx, req.(*GetNcountAccountInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_SetPaymentSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPaymentSecretReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).SetPaymentSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_SetPaymentSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).SetPaymentSecret(ctx, req.(*SetPaymentSecretReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trade_GetOpenIDByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenIDByCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServer).GetOpenIDByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trade_GetOpenIDByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServer).GetOpenIDByCode(ctx, req.(*GetOpenIDByCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Trade_ServiceDesc is the grpc.ServiceDesc for Trade service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trade_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_chess.Trade",
	HandlerType: (*TradeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "h5Prepaid",
			Handler:    _Trade_H5Prepaid_Handler,
		},
		{
			MethodName: "AppPrepaid",
			Handler:    _Trade_AppPrepaid_Handler,
		},
		{
			MethodName: "jsapiPrepaid",
			Handler:    _Trade_JsapiPrepaid_Handler,
		},
		{
			MethodName: "jsapiRepaid",
			Handler:    _Trade_JsapiRepaid_Handler,
		},
		{
			MethodName: "queryOrder",
			Handler:    _Trade_QueryOrder_Handler,
		},
		{
			MethodName: "cancelOrder",
			Handler:    _Trade_CancelOrder_Handler,
		},
		{
			MethodName: "refundOrder",
			Handler:    _Trade_RefundOrder_Handler,
		},
		{
			MethodName: "withdrawBankCard",
			Handler:    _Trade_WithdrawBankCard_Handler,
		},
		{
			MethodName: "queryExtractOrder",
			Handler:    _Trade_QueryExtractOrder_Handler,
		},
		{
			MethodName: "saveExtractConfig",
			Handler:    _Trade_SaveExtractConfig_Handler,
		},
		{
			MethodName: "getExtractConfig",
			Handler:    _Trade_GetExtractConfig_Handler,
		},
		{
			MethodName: "saveExtractUserConfig",
			Handler:    _Trade_SaveExtractUserConfig_Handler,
		},
		{
			MethodName: "getExtractUserConfig",
			Handler:    _Trade_GetExtractUserConfig_Handler,
		},
		{
			MethodName: "getExtractLogs",
			Handler:    _Trade_GetExtractLogs_Handler,
		},
		{
			MethodName: "checkUserExtractRisk",
			Handler:    _Trade_CheckUserExtractRisk_Handler,
		},
		{
			MethodName: "mallBookNewSelfAccount",
			Handler:    _Trade_MallBookNewSelfAccount_Handler,
		},
		{
			MethodName: "mallBookBindBankCard",
			Handler:    _Trade_MallBookBindBankCard_Handler,
		},
		{
			MethodName: "mallBookUnbindBankCard",
			Handler:    _Trade_MallBookUnbindBankCard_Handler,
		},
		{
			MethodName: "mallBookDeposit",
			Handler:    _Trade_MallBookDeposit_Handler,
		},
		{
			MethodName: "mallBookTransfer",
			Handler:    _Trade_MallBookTransfer_Handler,
		},
		{
			MethodName: "mallBookWithdraw",
			Handler:    _Trade_MallBookWithdraw_Handler,
		},
		{
			MethodName: "mallBookCheckUserAccountInfo",
			Handler:    _Trade_MallBookCheckUserAccountInfo_Handler,
		},
		{
			MethodName: "getNcountAccountInfo",
			Handler:    _Trade_GetNcountAccountInfo_Handler,
		},
		{
			MethodName: "setPaymentSecret",
			Handler:    _Trade_SetPaymentSecret_Handler,
		},
		{
			MethodName: "getOpenIDByCode",
			Handler:    _Trade_GetOpenIDByCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chess_trade.proto",
}
